---
title: "Anhedonia_SummaryTables"
author: "Katie Meeks"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
#For loop for matrices to run graph theory metrics on

all_ids <- c("hc_mat","mdd_mat","hc_mat_cingop","hc_mat_dmode", "hc_mat_dorsalatt","hc_mat_fpdm","hc_mat_frparietal","hc_mat_sali", "hc_mat_subc",
             "hc_mat2","hc_mat_cingop2","hc_mat_dmode2","hc_mat_dorsalatt2", "hc_mat_fpdm2","hc_mat_frparietal2","hc_mat_sali2", "hc_mat_subc2", 
             "mdd_mat", "mdd_mat_cingop","mdd_mat_dmode", "mdd_mat_dorsalatt","mdd_mat_fpdm","mdd_mat_frparietal","mdd_mat_sali","mdd_mat_subc",
             "mdt_mat","mdt_mat_cingop","mdt_mat_dmode", "mdt_mat_dorsalatt","mdt_mat_fpdm","mdt_mat_frparietal", "mdt_mat_sali","mdt_mat_subc",
             "trd_mat","trd_mat_cingop","trd_mat_dmode", "trd_mat_dorsalatt","trd_mat_fpdm","trd_mat_frparietal", "trd_mat_sali", "trd_mat_subc")

for (id in all_ids) 
{message <- paste0("trans_",id, "<- transitivity(i_",id,"_p)
                   pl_",id," <- mean_distance(i_",id,"_p, weights=NULL, unconnected=FALSE
                   d_",id," <- degree(i_",id,"_p)
                   md_",id," <- mean(d_",id,")"
                  ) 

print(message)}
```


```{r}
#For loops to run for Modularity calculations:
all_ids <- c("hc_mat_cingop","hc_mat_dmode", "hc_mat_dorsalatt","hc_mat_frparietal","hc_mat_sali", "hc_mat_subc",
            
             "mdd_mat_cingop","mdd_mat_dmode", "mdd_mat_dorsalatt","mdd_mat_frparietal","mdd_mat_sali","mdd_mat_subc"
            )

for (id in all_ids) 
{message <- paste0("wt_",id, "<- cluster_walktrap(i_",id,"_p, weights=NULL, steps=4)
                   member_",id," <- membership(wt_",id,")
                   mod_",id," <- modularity(i_",id,"_p, membership=member_",id,",weights=NULL, resolution=1)"
                  ) 

print(message)}


```

```{r}
#For loops to run for degree & centrality calculations:
all_ids <- c("hc_mat_cingop","hc_mat_dmode", "hc_mat_dorsalatt","hc_mat_fpdm","hc_mat_frparietal","hc_mat_saldm","hc_mat_sali", "hc_mat_subc",
             
             "mdd_mat_cingop","mdd_mat_dmode", "mdd_mat_dorsalatt","mdd_mat_fpdm","mdd_mat_frparietal","mdd_mat_saldm","mdd_mat_sali","mdd_mat_subc"
            )

for (id in all_ids) 
{message <- paste0("deg_",id, "<- degree(i_",id,"_p, v = V(i_",id,"_p))
                   btw_",id," <- betweenness(i_",id,"_p, v = V(i_",id,"_p))"
                   
                  ) 

print(message)}

```


```{r}
all_ids <- c("_mat_cingop","_mat_cingdm","_mat_dmode","_mat_dorsalatt","_mat_fpdm","_mat_frparietal","_mat_saldm","_mat_sali", "_mat_subc")

for (id in all_ids) 
{message <- paste0("t_btw_",id, "<- t.test(btw_hc",id,",btw_mdd",id,", alternative=^two.sided^,na.action=na.remove)
                   t_btw_",id,"$p.value
                   t_deg_",id," <- t.test(deg_hc",id,",deg_mdd" ,id,",alternative=^two.sided^,na.action=na.remove)
                  t_deg_",id,"$p.value"
                  )

print(message)}

```


```{r}
#Strength & p-values
all_ids <- c("_mat_cingop","_mat_cingdm","_mat_dmode","_mat_dorsalatt","_mat_fpdm","_mat_frparietal","_mat_saldm","_mat_sali", "_mat_subc")

for (id in all_ids) 
{message <- paste0("str_hc",id, "<- strength(i_hc",id,"_p)
                  str_mdd",id, "<- strength(i_mdd",id,"_p)

 t_str_",id," <- t.test(str_hc",id,",str_mdd",id,", alternative=^two.sided^,na.action=na.remove)
                   t_str_",id,"$p.value"
                  )

print(message)}

```

```{r}
##Mean betweenness calculations
all_ids <- c("hc_mat","mdd_mat","hc_mat_cingdm","hc_mat_cingop","hc_mat_dmode", "hc_mat_dorsalatt","hc_mat_fpdm","hc_mat_frparietal","hc_mat_saldm","hc_mat_sali", "hc_mat_subc",
             "mdd_mat", "mdd_mat_cingdm","mdd_mat_cingop", "mdd_mat_dmode", "mdd_mat_dorsalatt","mdd_mat_fpdm","mdd_mat_frparietal","mdd_mat_saldm","mdd_mat_sali","mdd_mat_subc"
            )

for (id in all_ids) 
{message <- paste0("mb_",id, "<- mean(btw_",id,")"
 
                   )

print(message)}
                  
```
```{r}
#Writing betweenness/centrality table
all_ids <- c("hc","mdd","hc_mat_cingdm","hc_mat_cingop","hc_mat_dmode", "hc_mat_dorsalatt","hc_mat_fpdm","hc_mat_frparietal","hc_mat_saldm","hc_mat_sali", "hc_mat_subc",
             "mdd_mat", "mdd_mat_cingdm","mdd_mat_cingop", "mdd_mat_dmode", "mdd_mat_dorsalatt","mdd_mat_fpdm","mdd_mat_frparietal","mdd_mat_saldm","mdd_mat_sali","mdd_mat_subc"
            )

for (id in all_ids) 
{message <- paste0("ms_",id,",mb_",id,", )"
 
                   )

print(message)}

```
```{r}
#Loop for Calculating Metrics for Individual Participants
all_ids <- c("801","814","815","893","915","932","942","821","823","825","831","834","848","849","857","858","860","878","879","884","904","906","918","931","939",  #mdd
             "822","829","833","837","845","855","859","864","867","868","882","883","890","894","895","899","901","916","921","937"  #hc
            )

for (id in all_ids) 
{message <- paste0("mat",id,"_p <- pmax(mat",id,",0)
                    mat",id,"[is.na(mat",id,")] <- 0
                    i_mat",id,"_p <- graph.adjacency(mat",id,"_p , mode = 'undirected', weighted = TRUE)
                                      d_",id," <- degree(i_mat",id,"_p)
                   md_",id," <- mean(d_",id,")
                   
                   mod_",id," <- modularity(i_mat",id,"_p, membership=groupvector, weights=NULL, resolution=1)
                   
                   str_",id," <- strength(i_mat",id,"_p)
                   ms_",id," <- mean(str_",id,")"
)

print(message)}
```

```{r}
all_ids <- c("801","814","815","893","915","932","942","821","823","825","831","834","848","849","857","858","860","878","879","884","904","906","918","931","939",  #mdd
             "822","829","833","837","845","855","859","864","867","868","882","883","890","894","895","899","901","916","921","937"  #hc
            )

for (id in all_ids) 
{message <- paste0("'",id,"'"
)

print(message)}
```

```{r}
all_ids <- c("801","814","815","893","915","932","942","821","823","825","831","834","848","849","857","858","860","878","879","884","904","906","918","931","939",  #mdd
             "822","829","833","837","845","855","859","864","867","868","882","883","890","894","895","899","901","916","921","937"  #hc
            )

for (id in all_ids) 
{message <- paste0("md_",id,",
                   mod_",id,",
                   ms_",id,","
)

print(message)}
```


```{r}
mat_p <- pmax(hc_mat,0) #turn matrix into all positive values
i_hc_mat_p <- graph.adjacency(hc_mat_p,mode='undirected',weighted=TRUE) #convert to igraph object

pl_hc <- mean_distance(i_hc_mat_p, weights=NULL, unconnected=FALSE)

d_hc <- degree(i_hc_mat_p) 
md_hc <- mean(d_hc)

groupvector <- c(1,1,1,1,1,1,1,1,1,1,1,1,1,1,
                 2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,
                 3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,
                 4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,
                 5,5,5,5,5,5,5,5,5,5,5,5,5,
                 6,6,6,6,6,6,6,6,6,6,6)  #1 = cingop, 2=dm, 3=fp, 4=sali, 5=subc, 6=dorsalatt
mod_hc <- modularity(i_hc_mat_p, membership=groupvector, weights=NULL, resolution=1)

str_mdd_mat<- strength(i_mdd_mat_p)
ms_mdd <- mean(str_mdd_mat)

btw_hc_mat_cingdm <- betweenness(i_hc_mat_cingdm_p, v = V(i_hc_mat_cingdm_p))
mb_hc<- mean(btw_hc)
```


```{r}
############### biological correlates ################
library('tidyverse')

setwd("C:/Users/Katie/OneDrive - The Pennsylvania State University/b-geierlab Shared/Anhedonia/Cleaning&Analysis")

#Reading the file with all participants data
dat = read.csv("C:/Users/Katie/OneDrive - The Pennsylvania State University/b-geierlab Shared/Anhedonia/Cleaning&Analysis/All_Metrics_2.csv",header = TRUE)
head(dat)
str(dat)

cor_df = subset(dat, select =  c("type","relMean","relMax","madrs","shaps"))

head(cor_df)

#Correlation:
    #cor(cor_df,use="pairwise.complete.obs")    #this isn't working; I think 'cor' requires two columns for input, not a whole data frame

#Checking for NA values:
#sum(is.na(cor_df["dars"]))

#Correlation plot - for motion & group/madrs/shaps
pairs(cor_df)

#Correlation plot - for FC metrics predicting group/depression
dat2 = read.csv("C:/Users/Katie/OneDrive - The Pennsylvania State University/b-geierlab Shared/Anhedonia/Cleaning&Analysis/All_Metrics_3.csv",header = TRUE)
head(dat2)
str(dat2)

cor_df2 = subset(dat2, select =  c("type","madrs","fc","mdeg","mod","ms"))
head(cor_df2)
pairs(cor_df2)


#Correlation plot - for FC metrics predicting group/depression
cor_df2 = subset(dat2, select =  c("shaps","dars","teps","fc","mdeg","mod","ms"))
head(cor_df2)
pairs(cor_df2)


mod1 = lm(dat2$relMean ~ dat2$type)
mod1sum <- summary(mod1)

mod2 = lm(dat2$relMax ~ dat2$type)
mod2sum <- summary(mod2)

mod3 = lm(dat2$madrs ~ dat2$type)
mod3sum <- summary(mod3)

mod4 = lm(dathyp2$shaps ~ dathyp2$type)
mod4sum <- summary(mod4)

mod5 = lm(dat2$dars ~ dat2$type)
mod5sum <- summary(mod5)

mod6 = lm(dat2$teps ~ dat2$type)
mod6sum <- summary(mod6)

mod7 = lm(dat2$fc ~ dat2$type)
mod7sum <- summary(mod7)

mod8 = lm(dat2$mdeg ~ dat2$type)
mod8sum <- summary(mod8)

mod9 = lm(dat2$mod ~ dat2$type)
mod9sum <- summary(mod9)

mod10 = lm(dat2$ms ~ dat2$type)
mod10sum <- summary(mod10)

mod11 = lm(dat2$madrs ~ dat2$fc + dat2$mdeg + dat2$mod + dat2$ms) #all graph theory measures
mod11sum <- summary(mod11)

############ with #855 removed   [I think it was an outlier on the madrs plot and Dr. Geier wanted to check if correlation still held with it removed]
dat2ed <- dat2$subj !=  "855" 

    mod11 = lm(dat2$madrs ~ dat2$fc + dat2$mdeg + dat2$mod + dat2$ms) #all graph     theory measures
    mod11sum <- summary(mod11)
############

mod12 = lm(dathyp2$shaps ~ dathyp2$fc)
mod12sum <- summary(mod12)

mod13 = lm(dathyp2$shaps ~ dathyp2$fc + dathyp2$mdeg + dathyp2$mod + dathyp2$ms) #all graph theory measures
mod13sum <- summary(mod13)

#### more models for individual graph metrics predicting 'type' and/or 'shaps' or other anhedonia measures

mod14 = lm(dathyp2$shaps ~ dathyp2$mdeg)
mod14sum <- summary(mod14)

mod15 = lm(dathyp2$shaps ~ dathyp2$mod)
mod15sum <- summary(mod15)

mod16 = lm(dathyp2$shaps ~ dathyp2$ms)
mod16sum <- summary(mod16)

mod17 = lm(dat2$antic ~ dat2$fc + dat2$mdeg + dat2$mod + dat2$ms) #all graph theory measures
mod17sum <- summary(mod17)

mod18 = lm(dat2$dars ~ dat2$fc + dat2$mdeg + dat2$mod + dat2$ms) #all graph theory measures
mod18sum <- summary(mod18)

mod19 = lm(dat2$teps ~ dat2$fc + dat2$mdeg + dat2$mod + dat2$ms) #all graph theory measures
mod19sum <- summary(mod19)

mod20 = lm(dat2$consum ~ dat2$fc + dat2$mdeg + dat2$mod + dat2$ms) #all graph theory measures
mod20sum <- summary(mod20)


summary(mod18)
summary(mod19)
summary(mod20)


##### Models looking at between-network connectivity predicting anhedonia ####
dathyp2 = read.csv("C:/Users/Katie/OneDrive - The Pennsylvania State University/b-geierlab Shared/Anhedonia/Cleaning&Analysis/fc_indiv_btwnet_regression.csv",header = TRUE)
head(dathyp2)
str(dathyp2)

cor_df4 = subset(dathyp2, select =  c("type","relMean","relMax","madrs","shaps"))
pairs(cor_df4)

cor_df5 = subset(dathyp2, select =  c("shaps","dars","teps","fc","mdeg","mod","ms"))
head(cor_df5)
pairs(cor_df5)


mod21 = lm(dathyp2$Meanfpdm ~ dathyp2$shaps)
mod22 = lm(dathyp2$Meanfpdm ~ dathyp2$dars)
mod23 = lm(dathyp2$Meanfpdm ~ dathyp2$teps)
mod24 = lm(dathyp2$Meanfpdm ~ dathyp2$antic)
mod25 = lm(dathyp2$Meanfpdm ~ dathyp2$consum)

mod26 = lm(dathyp2$Meancingdm ~ dathyp2$shaps)
mod27 = lm(dathyp2$Meancingdm ~ dathyp2$dars)
mod28 = lm(dathyp2$Meancingdm ~ dathyp2$teps)
mod29 = lm(dathyp2$Meancingdm ~ dathyp2$antic)
mod30 = lm(dathyp2$Meancingdm ~ dathyp2$consum)

mod31 = lm(dathyp2$Meansaldm ~ dathyp2$shaps)
mod32 = lm(dathyp2$Meansaldm ~ dathyp2$dars)
mod33 = lm(dathyp2$Meansaldm ~ dathyp2$teps)
mod34 = lm(dathyp2$Meansaldm ~ dathyp2$antic)
mod35 = lm(dathyp2$Meansaldm ~ dathyp2$consum)


mod21sum <- summary(mod21)
mod22sum <- summary(mod22)
mod23sum <- summary(mod23)
mod24sum <- summary(mod24)
mod25sum <- summary(mod25)
mod26sum <- summary(mod26)
mod27sum <- summary(mod27)
mod28sum <- summary(mod28)
mod29sum <- summary(mod29)
mod30sum <- summary(mod30)
mod31sum <- summary(mod31)
mod32sum <- summary(mod32)
mod33sum <- summary(mod33)
mod34sum <- summary(mod34)
mod35sum <- summary(mod35)
```

```{r}
#for loop to get all intercepts, coefficients, SE, t-values, and p-values for all models:
  #"mod18","mod19","mod20"
all_ids <- c("mod1", "mod2", "mod3", "mod4", "mod5", "mod6", "mod7", "mod8", "mod9", "mod10",  "mod11", "mod12",  "mod13", "mod14", "mod15", "mod16", "mod17"
            )

for (id in all_ids) 
{message <- paste0(id,"sum$coefficients[1,1],",id,"sum$coefficients[1,2],",id,"sum$coefficients[1,3],",id,"sum$coefficients[1,4],",id,"sum$coefficients[2,1],",id,"sum$coefficients[2,2],",id,"sum$coefficients[2,3],",id,"sum$coefficients[2,4],"
)

print(message)}


####### models with >1 fixed effect #######
all_ids <- c( "mod11", "mod13", "mod17"
            )

for (id in all_ids) 
{message <- paste0(id,"sum$coefficients[3,1],",id,"sum$coefficients[3,2],",id,"sum$coefficients[3,3],",id,"sum$coefficients[3,4],",id,"sum$coefficients[4,1],",id,"sum$coefficients[4,2],",id,"sum$coefficients[4,3],",id,"sum$coefficients[4,4],",id,"sum$coefficients[5,1],",id,"sum$coefficients[5,2],",id,"sum$coefficients[5,3],",id,"sum$coefficients[5,4],"
)

print(message)}
```


```{r}
##### make a table of regression models #####

tab_reg <- matrix(c(mod1sum$coefficients[1,1],mod1sum$coefficients[1,2],mod1sum$coefficients[1,3],mod1sum$coefficients[1,4],mod1sum$coefficients[2,1],mod1sum$coefficients[2,2],mod1sum$coefficients[2,3],mod1sum$coefficients[2,4],

mod2sum$coefficients[1,1],mod2sum$coefficients[1,2],mod2sum$coefficients[1,3],mod2sum$coefficients[1,4],mod2sum$coefficients[2,1],mod2sum$coefficients[2,2],mod2sum$coefficients[2,3],mod2sum$coefficients[2,4],

mod3sum$coefficients[1,1],mod3sum$coefficients[1,2],mod3sum$coefficients[1,3],mod3sum$coefficients[1,4],mod3sum$coefficients[2,1],mod3sum$coefficients[2,2],mod3sum$coefficients[2,3],mod3sum$coefficients[2,4],

mod4sum$coefficients[1,1],mod4sum$coefficients[1,2],mod4sum$coefficients[1,3],mod4sum$coefficients[1,4],mod4sum$coefficients[2,1],mod4sum$coefficients[2,2],mod4sum$coefficients[2,3],mod4sum$coefficients[2,4],

mod5sum$coefficients[1,1],mod5sum$coefficients[1,2],mod5sum$coefficients[1,3],mod5sum$coefficients[1,4],mod5sum$coefficients[2,1],mod5sum$coefficients[2,2],mod5sum$coefficients[2,3],mod5sum$coefficients[2,4],

mod6sum$coefficients[1,1],mod6sum$coefficients[1,2],mod6sum$coefficients[1,3],mod6sum$coefficients[1,4],mod6sum$coefficients[2,1],mod6sum$coefficients[2,2],mod6sum$coefficients[2,3],mod6sum$coefficients[2,4],

mod7sum$coefficients[1,1],mod7sum$coefficients[1,2],mod7sum$coefficients[1,3],mod7sum$coefficients[1,4],mod7sum$coefficients[2,1],mod7sum$coefficients[2,2],mod7sum$coefficients[2,3],mod7sum$coefficients[2,4],

mod8sum$coefficients[1,1],mod8sum$coefficients[1,2],mod8sum$coefficients[1,3],mod8sum$coefficients[1,4],mod8sum$coefficients[2,1],mod8sum$coefficients[2,2],mod8sum$coefficients[2,3],mod8sum$coefficients[2,4],

mod9sum$coefficients[1,1],mod9sum$coefficients[1,2],mod9sum$coefficients[1,3],mod9sum$coefficients[1,4],mod9sum$coefficients[2,1],mod9sum$coefficients[2,2],mod9sum$coefficients[2,3],mod9sum$coefficients[2,4],

mod10sum$coefficients[1,1],mod10sum$coefficients[1,2],mod10sum$coefficients[1,3],mod10sum$coefficients[1,4],mod10sum$coefficients[2,1],mod10sum$coefficients[2,2],mod10sum$coefficients[2,3],mod10sum$coefficients[2,4],

mod11sum$coefficients[1,1],mod11sum$coefficients[1,2],mod11sum$coefficients[1,3],mod11sum$coefficients[1,4],mod11sum$coefficients[2,1],mod11sum$coefficients[2,2],mod11sum$coefficients[2,3],mod11sum$coefficients[2,4],mod11sum$coefficients[3,1],mod11sum$coefficients[3,2],mod11sum$coefficients[3,3],mod11sum$coefficients[3,4],mod11sum$coefficients[4,1],mod11sum$coefficients[4,2],mod11sum$coefficients[4,3],mod11sum$coefficients[4,4],mod11sum$coefficients[5,1],mod11sum$coefficients[5,2],mod11sum$coefficients[5,3],mod11sum$coefficients[5,4],

mod12sum$coefficients[1,1],mod12sum$coefficients[1,2],mod12sum$coefficients[1,3],mod12sum$coefficients[1,4],mod12sum$coefficients[2,1],mod12sum$coefficients[2,2],mod12sum$coefficients[2,3],mod12sum$coefficients[2,4],

mod13sum$coefficients[1,1],mod13sum$coefficients[1,2],mod13sum$coefficients[1,3],mod13sum$coefficients[1,4],mod13sum$coefficients[2,1],mod13sum$coefficients[2,2],mod13sum$coefficients[2,3],mod13sum$coefficients[2,4],mod13sum$coefficients[3,1],mod13sum$coefficients[3,2],mod13sum$coefficients[3,3],mod13sum$coefficients[3,4],mod13sum$coefficients[4,1],mod13sum$coefficients[4,2],mod13sum$coefficients[4,3],mod13sum$coefficients[4,4],mod13sum$coefficients[5,1],mod13sum$coefficients[5,2],mod13sum$coefficients[5,3],mod13sum$coefficients[5,4],

mod14sum$coefficients[1,1],mod14sum$coefficients[1,2],mod14sum$coefficients[1,3],mod14sum$coefficients[1,4],mod14sum$coefficients[2,1],mod14sum$coefficients[2,2],mod14sum$coefficients[2,3],mod14sum$coefficients[2,4],

mod15sum$coefficients[1,1],mod15sum$coefficients[1,2],mod15sum$coefficients[1,3],mod15sum$coefficients[1,4],mod15sum$coefficients[2,1],mod15sum$coefficients[2,2],mod15sum$coefficients[2,3],mod15sum$coefficients[2,4],

mod16sum$coefficients[1,1],mod16sum$coefficients[1,2],mod16sum$coefficients[1,3],mod16sum$coefficients[1,4],mod16sum$coefficients[2,1],mod16sum$coefficients[2,2],mod16sum$coefficients[2,3],mod16sum$coefficients[2,4],

mod17sum$coefficients[1,1],mod17sum$coefficients[1,2],mod17sum$coefficients[1,3],mod17sum$coefficients[1,4],mod17sum$coefficients[2,1],mod17sum$coefficients[2,2],mod17sum$coefficients[2,3],mod17sum$coefficients[2,4],mod17sum$coefficients[3,1],mod17sum$coefficients[3,2],mod17sum$coefficients[3,3],mod17sum$coefficients[3,4],mod17sum$coefficients[4,1],mod17sum$coefficients[4,2],mod17sum$coefficients[4,3],mod17sum$coefficients[4,4],mod17sum$coefficients[5,1],mod17sum$coefficients[5,2],mod17sum$coefficients[5,3],mod17sum$coefficients[5,4]), ncol=4, byrow=TRUE)
colnames(tab_reg) <- c('Est','SE','t value','p-value')
rownames(tab_reg) <- c('mod1','mod1','mod2','mod2','mod3','mod3','mod4','mod4','mod5','mod5','mod6','mod6','mod7','mod7','mod8','mod8','mod9','mod9','mod10','mod10','mod11','mod11','mod11','mod11','mod11','mod12','mod12','mod13','mod13','mod13','mod13','mod13','mod14','mod14','mod15','mod15','mod16','mod16','mod17','mod17','mod17','mod17','mod17')
write.table(tab_reg, file='C:/Users/Katie/OneDrive - The Pennsylvania State University/b-geierlab Shared/Anhedonia/Cleaning&Analysis/SummaryTables/regression.csv')
```

```{r}
#Adding to plot 5d:
tab_reg2 <- matrix(c(mod18sum$coefficients[1,1],mod18sum$coefficients[1,2],mod18sum$coefficients[1,3],mod18sum$coefficients[1,4],mod18sum$coefficients[2,1],mod18sum$coefficients[2,2],mod18sum$coefficients[2,3],mod18sum$coefficients[2,4],mod18sum$coefficients[3,1],mod18sum$coefficients[3,2],mod18sum$coefficients[3,3],mod18sum$coefficients[3,4],mod18sum$coefficients[4,1],mod18sum$coefficients[4,2],mod18sum$coefficients[4,3],mod18sum$coefficients[4,4],mod18sum$coefficients[5,1],mod18sum$coefficients[5,2],mod18sum$coefficients[5,3],mod18sum$coefficients[5,4],

mod19sum$coefficients[1,1],mod19sum$coefficients[1,2],mod19sum$coefficients[1,3],mod19sum$coefficients[1,4],mod19sum$coefficients[2,1],mod19sum$coefficients[2,2],mod19sum$coefficients[2,3],mod19sum$coefficients[2,4],mod19sum$coefficients[3,1],mod19sum$coefficients[3,2],mod19sum$coefficients[3,3],mod19sum$coefficients[3,4],mod19sum$coefficients[4,1],mod19sum$coefficients[4,2],mod19sum$coefficients[4,3],mod19sum$coefficients[4,4],mod19sum$coefficients[5,1],mod19sum$coefficients[5,2],mod19sum$coefficients[5,3],mod19sum$coefficients[5,4],

mod20sum$coefficients[1,1],mod20sum$coefficients[1,2],mod20sum$coefficients[1,3],mod20sum$coefficients[1,4],mod20sum$coefficients[2,1],mod20sum$coefficients[2,2],mod20sum$coefficients[2,3],mod20sum$coefficients[2,4],mod20sum$coefficients[3,1],mod20sum$coefficients[3,2],mod20sum$coefficients[3,3],mod20sum$coefficients[3,4],mod20sum$coefficients[4,1],mod20sum$coefficients[4,2],mod20sum$coefficients[4,3],mod20sum$coefficients[4,4],mod20sum$coefficients[5,1],mod20sum$coefficients[5,2],mod20sum$coefficients[5,3],mod20sum$coefficients[5,4]
), ncol=4, byrow=TRUE)
colnames(tab_reg2) <- c('Est','SE','t value','p-value')
rownames(tab_reg2) <- c('mod18','mod18','mod18','mod18','mod18','mod19','mod19','mod19','mod19','mod19','mod20','mod20','mod20','mod20','mod20')
write.table(tab_reg2, file='C:/Users/Katie/OneDrive - The Pennsylvania State University/b-geierlab Shared/Anhedonia/Cleaning&Analysis/SummaryTables/regression_5d.csv')
```



```{r}
#making interindividual regression plots
ggplot(data = dat2, aes(x = mdeg, y = madrs)) +
  geom_point() + 
  geom_smooth(method="lm", formula= y ~ 1 + x, 
              se=TRUE, fullrange=TRUE, color="purple", linewidth=2) +
  xlab("mean degree") + 
  ylab("Total MADRS score") +
  ggtitle("Mean Degree Predicts Depression Severity (MADRS Score)")

#####
#making interindividual regression plots (with #855 removed)   [I think #855 was an outlier on the madrs plot and Dr. Geier wanted to check if correlation still held with it removed]
#dat2.2 <- dat2
dat2 %>% 
  filter(subj != "855") %>%
ggplot(aes(x = mdeg, y = madrs)) +
  geom_point() + 
  geom_smooth(method="lm", formula= y ~ 1 + x, 
              se=TRUE, fullrange=TRUE, color="purple", linewidth=2) +
  xlab("mean degree") + 
  ylab("Total MADRS score") +
  ggtitle("Mean Degree Predicts Depression Severity (MADRS Score)")
#####


ggplot(data = dat2, aes(x = mdeg, y = shaps)) +
  geom_point() + 
  geom_smooth(method="lm", formula= y ~ 1 + x, 
              se=TRUE, fullrange=TRUE, color="purple", size=2) +
  xlab("mean degree") + 
  ylab("Total SHAPS score") +
  ggtitle("Mean Degree Predicts Anhedonia Severity (SHAPS Score)")



ggplot(data = dat2, aes(x = mod, y = shaps)) +
  geom_point() + 
  geom_smooth(method="lm", formula= y ~ 1 + x, 
              se=TRUE, fullrange=TRUE, color="purple", size=2) +
  xlab("modularity") + 
  ylab("Total SHAPS score") +
  ggtitle("Modularity Predicts Anhedonia Severity (SHAPS Score)")

### Including 893 SHAPS score ###
ggplot(data = dathyp2, aes(x = mdeg, y = shaps)) +
  geom_point() + 
  geom_smooth(method="lm", formula= y ~ 1 + x, 
              se=TRUE, fullrange=TRUE, color="purple", size=2) +
  xlab("mean degree") + 
  ylab("Total SHAPS score") +
  ggtitle("Mean Degree Predicts Anhedonia Severity (SHAPS Score)")
#### THIS One is no longer significant when you add in #893s SHAPS Score (except within full model)


ggplot(data = dathyp2, aes(x = mod, y = shaps)) +
  geom_point() + 
  geom_smooth(method="lm", formula= y ~ 1 + x, 
              se=TRUE, fullrange=TRUE, color="purple", size=2) +
  xlab("modularity") + 
  ylab("Total SHAPS score") +
  ggtitle("Modularity Predicts Anhedonia Severity (SHAPS Score)")


#making interindividual regression plots for between-network FC:
ggplot(data = dathyp2, aes(x = shaps, y = Meancingdm)) +
  geom_point() + 
  geom_smooth(method="lm", formula= y ~ 1 + x, 
              se=TRUE, fullrange=TRUE, color="purple", linewidth=2) +
  xlab("Anhedonia score (SHAPS)") + 
  ylab("Salience network and DMN FC") +
  ggtitle("Anhedonia (SHAPS) Predicts Salience network and DMN FC")


ggplot(data = dathyp2, aes(x = consum, y = Meanfpdm)) +
  geom_point() + 
  geom_smooth(method="lm", formula= y ~ 1 + x, 
              se=TRUE, fullrange=TRUE, color="purple", linewidth=2) +
  xlab("Consummatory Anhedonia score (TEPS)") + 
  ylab("Fronto-parietal network and DMN FC") +
  ggtitle("Consummatory Anhedonia Predicts Fronto-parietal network and DMN FC")
```


```{r}
all_ids <- c("801","814","815","893","915","932","942","821","823","825","831","834","848","849","857","858","860","878","879","884","904","906","918","931","939",  #mdd
             "822","829","833","837","845","855","864","867","868","882","883","890","894","895","899","901","916","921","937"  #hc (not including #859)
            )

for (id in all_ids) 
{message <- paste0("md_",id,",
                   mod_",id,",
                   ms_",id,","
)

print(message)}


 t_str__mat_subc <- t.test(str_hc_mat_subc,str_mdd_mat_subc, alternative="two.sided",na.action=na.remove)
                   t_str__mat_subc$p.value
```


```{r}
all_ids <- c("801","814","815","893","915","932","942","821","823","825","831","834","848","849","857","858","860","878","879","884","904","906","918","931","939",  #mdd
             "822","829","833","837","845","855","864","867","868","882","883","890","894","895","899","901","916","921","937"  #hc (not including #859)
            )

for (id in all_ids) 
{message <- paste0("mat",id,"_dm_p <- pmax(mat",id,"_dmode,0)
                   mat",id,"_fp_p <- pmax(mat",id,"_frparietal,0)"
)

print(message)}
```


```{r}
all_ids <- c("801","814","815","893","915","932","942","821","823","825","831","834","848","849","857","858","860","878","879","884","904","906","918","931","939",  #mdd
             "822","829","833","837","845","855","864","867","868","882","883","890","894","895","899","901","916","921","937"  #hc (not including #859)
            )

for (id in all_ids) 
{message <- paste0("mean_dm",id," <- mean(mat",id,"_dm_p,na.rm = TRUE)
                   mean_fp",id," <- mean(mat",id,"_fp_p,na.rm = TRUE)"
)

print(message)}



all_ids <- c("801","814","815","893","915","932","942","821","823","825","831","834","848","849","857","858","860","878","879","884","904","906","918","931","939",  #mdd
             "822","829","833","837","845","855","864","867","868","882","883","890","894","895","899","901","916","921","937"  #hc (not including #859)
            )

for (id in all_ids) 
{message <- paste0("mean_dm",id,", mean_fp",id
)

print(message)}
```

```{r}
### A few more regression models -- MADRS predicted by dm or fp FC? ###
datnet = read.csv("C:/Users/Katie/OneDrive - The Pennsylvania State University/b-geierlab Shared/Anhedonia/Cleaning&Analysis/dm_fp_fc.csv",header = TRUE)
head(datnet)
str(datnet)

cor_datnet = subset(datnet, select =  c("madrs","dm_fc","fp_fc"))
head(cor_datnet)
pairs(cor_datnet)


moddm = lm(datnet$madrs ~ datnet$dm_fc)
moddm_sum <- summary(moddm)
moddm_sum$p.value

modfp = lm(datnet$madrs ~ datnet$fp_fc)
modfp_sum <- summary(modfp)
modfp_sum$p.value
```

```{r}
#For loops for making between-network matrices:
all_ids <- c("814","815","893","915","932","942","821","823","825","831","834","848","849","857","858","860","878","879","884","904","906","918","931","939",  #mdd
             "822","829","833","837","845","855","864","867","868","882","883","890","894","895","899","901","916","921","937"  #hc (not including #859)
            )

for (id in all_ids) 
{message <- paste0("mat",id,"_fpdm <- cor(dat",id,"[,15:97], 
                     use = ^na.or.complete^)
                   mat",id,"_cingdm <- cor(dat",id,"[,1:72], 
                     use = ^na.or.complete^)
                   mat",id,"_saldm <- cor(cbind((dat",id,"[,15:72]),(dat",id,"[,98:115])), use = ^na.or.complete^)

                  mat",id,"_fpdm <- as.matrix(mat",id,"_fpdm)
                  mat",id,"_cingdm <- as.matrix(mat",id,"_cingdm)
                  mat",id,"_saldm <- as.matrix(mat",id,"_saldm)"
)

print(message)}

```

```{r}
#Changing between-network matrices to positive
all_ids <- c("801","814","815","893","915","932","942","821","823","825","831","834","848","849","857","858","860","878","879","884","904","906","918","931","939",  #mdd
             "822","829","833","837","845","855","864","867","868","882","883","890","894","895","899","901","916","921","937"  #hc (not including #859)
            )

for (id in all_ids) 
{message <- paste0("mat",id,"_fpdm_p <- pmax(mat",id,"_fpdm,0)
                   mat",id,"_cingdm_p <- pmax(mat",id,"_cingdm,0)
                   mat",id,"_saldm_p <- pmax(mat",id,"_saldm,0)

                  mat",id,"_fpdm <- as.matrix(mat",id,"_fpdm)
                  mat",id,"_cingdm <- as.matrix(mat",id,"_cingdm)
                  mat",id,"_saldm <- as.matrix(mat",id,"_saldm)"
)

print(message)}


```


```{r}
all_ids <- c("801","814","815","893","915","932","942","821","823","825","831","834","848","849","857","858","860","878","879","884","904","906","918","931","939",  #mdd
             "822","829","833","837","845","855","864","867","868","882","883","890","894","895","899","901","916","921","937"  #hc (not including #859)
            )

for (id in all_ids) 
{message <- paste0("mean_fpdm",id," <- mean(mat",id,"_fpdm_p, na.rm = TRUE) 
                  std_fpdm",id," <- SD(mat",id,"_fpdm_p, na.rm = TRUE)
                  stdev_fpdm",id," <- mean(std_fpdm",id,", na.rm = TRUE)
                  
                  mean_cingdm",id," <- mean(mat",id,"_cingdm_p,na.rm = TRUE) 
                  std_cingdm",id," <- SD(mat",id,"_cingdm_p, na.rm = TRUE)
                  stdev_cingdm",id," <- mean(std_cingdm",id,", na.rm = TRUE)
                  
                  mean_saldm",id," <- mean(mat",id,"_saldm_p,na.rm = TRUE) 
                  std_saldm",id," <- SD(mat",id,"_saldm_p,na.rm = TRUE)
                  stdev_saldm",id," <- mean(std_saldm",id,",na.rm = TRUE)"
)

print(message)}

```


```{r}
#for loop to get all intercepts, coefficients, SE, t-values, and p-values for all models:
  #"mod21" to "mod35"
all_ids <- c("mod21", "mod22", "mod23", "mod24", "mod25", "mod26", "mod27", "mod28", "mod29", "mod30",  "mod31", "mod32",  "mod33", "mod34", "mod35"
            )

for (id in all_ids) 
{message <- paste0(id,"sum$coefficients[1,1],",id,"sum$coefficients[1,2],",id,"sum$coefficients[1,3],",id,"sum$coefficients[1,4],",id,"sum$coefficients[2,1],",id,"sum$coefficients[2,2],",id,"sum$coefficients[2,3],",id,"sum$coefficients[2,4],"
)

print(message)}
```


```{r}
tab_reg5g <- matrix(c(mod21sum$coefficients[1,1],mod21sum$coefficients[1,2],mod21sum$coefficients[1,3],mod21sum$coefficients[1,4],mod21sum$coefficients[2,1],mod21sum$coefficients[2,2],mod21sum$coefficients[2,3],mod21sum$coefficients[2,4],

mod22sum$coefficients[1,1],mod22sum$coefficients[1,2],mod22sum$coefficients[1,3],mod22sum$coefficients[1,4],mod22sum$coefficients[2,1],mod22sum$coefficients[2,2],mod22sum$coefficients[2,3],mod22sum$coefficients[2,4],

mod23sum$coefficients[1,1],mod23sum$coefficients[1,2],mod23sum$coefficients[1,3],mod23sum$coefficients[1,4],mod23sum$coefficients[2,1],mod23sum$coefficients[2,2],mod23sum$coefficients[2,3],mod23sum$coefficients[2,4],

mod24sum$coefficients[1,1],mod24sum$coefficients[1,2],mod24sum$coefficients[1,3],mod24sum$coefficients[1,4],mod24sum$coefficients[2,1],mod24sum$coefficients[2,2],mod24sum$coefficients[2,3],mod24sum$coefficients[2,4],

mod25sum$coefficients[1,1],mod25sum$coefficients[1,2],mod25sum$coefficients[1,3],mod25sum$coefficients[1,4],mod25sum$coefficients[2,1],mod25sum$coefficients[2,2],mod25sum$coefficients[2,3],mod25sum$coefficients[2,4],

mod26sum$coefficients[1,1],mod26sum$coefficients[1,2],mod26sum$coefficients[1,3],mod26sum$coefficients[1,4],mod26sum$coefficients[2,1],mod26sum$coefficients[2,2],mod26sum$coefficients[2,3],mod26sum$coefficients[2,4],

mod27sum$coefficients[1,1],mod27sum$coefficients[1,2],mod27sum$coefficients[1,3],mod27sum$coefficients[1,4],mod27sum$coefficients[2,1],mod27sum$coefficients[2,2],mod27sum$coefficients[2,3],mod27sum$coefficients[2,4],

mod28sum$coefficients[1,1],mod28sum$coefficients[1,2],mod28sum$coefficients[1,3],mod28sum$coefficients[1,4],mod28sum$coefficients[2,1],mod28sum$coefficients[2,2],mod28sum$coefficients[2,3],mod28sum$coefficients[2,4],

mod29sum$coefficients[1,1],mod29sum$coefficients[1,2],mod29sum$coefficients[1,3],mod29sum$coefficients[1,4],mod29sum$coefficients[2,1],mod29sum$coefficients[2,2],mod29sum$coefficients[2,3],mod29sum$coefficients[2,4],

mod30sum$coefficients[1,1],mod30sum$coefficients[1,2],mod30sum$coefficients[1,3],mod30sum$coefficients[1,4],mod30sum$coefficients[2,1],mod30sum$coefficients[2,2],mod30sum$coefficients[2,3],mod30sum$coefficients[2,4],

mod31sum$coefficients[1,1],mod31sum$coefficients[1,2],mod31sum$coefficients[1,3],mod31sum$coefficients[1,4],mod31sum$coefficients[2,1],mod31sum$coefficients[2,2],mod31sum$coefficients[2,3],mod31sum$coefficients[2,4],

mod32sum$coefficients[1,1],mod32sum$coefficients[1,2],mod32sum$coefficients[1,3],mod32sum$coefficients[1,4],mod32sum$coefficients[2,1],mod32sum$coefficients[2,2],mod32sum$coefficients[2,3],mod32sum$coefficients[2,4],

mod33sum$coefficients[1,1],mod33sum$coefficients[1,2],mod33sum$coefficients[1,3],mod33sum$coefficients[1,4],mod33sum$coefficients[2,1],mod33sum$coefficients[2,2],mod33sum$coefficients[2,3],mod33sum$coefficients[2,4],

mod34sum$coefficients[1,1],mod34sum$coefficients[1,2],mod34sum$coefficients[1,3],mod34sum$coefficients[1,4],mod34sum$coefficients[2,1],mod34sum$coefficients[2,2],mod34sum$coefficients[2,3],mod34sum$coefficients[2,4],

mod35sum$coefficients[1,1],mod35sum$coefficients[1,2],mod35sum$coefficients[1,3],mod35sum$coefficients[1,4],mod35sum$coefficients[2,1],mod35sum$coefficients[2,2],mod35sum$coefficients[2,3],mod35sum$coefficients[2,4]), ncol=4, byrow=TRUE)
colnames(tab_reg5g) <- c('Est','SE','t value','p-value')
rownames(tab_reg5g) <- c('mod21','mod21','mod22','mod22','mod23','mod23','mod24','mod24','mod25','mod25','mod26','mod26','mod27','mod27','mod28','mod28','mod29','mod29','mod30','mod30','mod31','mod31','mod32','mod32','mod33','mod33','mod34','mod34','mod35','mod35')
write.table(tab_reg5g, file='C:/Users/Katie/OneDrive - The Pennsylvania State University/b-geierlab Shared/Anhedonia/Cleaning&Analysis/SummaryTables/regression_5g.csv')

```


```{r}
############## RE-DO of regression analyses with 893's SHAPS score ##############

#Correlation plot - for FC metrics predicting group/depression
dat4 = read.csv("C:/Users/Katie/OneDrive - The Pennsylvania State University/b-geierlab Shared/Anhedonia/Cleaning&Analysis/All_Metrics_4.csv",header = TRUE)
head(dat4)
str(dat4)


#Correlation plot - for FC metrics predicting group/depression
cor_df4 = subset(dat4, select =  c("shaps","dars","teps","fc","mdeg","mod","ms"))
head(cor_df4)
pairs(cor_df4)


mod1z = lm(dat4$relMean ~ dat4$type)
mod1zsum <- summary(mod1z)

mod2z = lm(dat4$relMax ~ dat4$type)
mod2zsum <- summary(mod2z)

mod3z = lm(dat4$madrs ~ dat4$type)
mod3zsum <- summary(mod3z)

mod4z = lm(dat4$shaps ~ dat4$type)
mod4zsum <- summary(mod4z)
mod4zsum$coefficients[2,3]

mod5z = lm(dat4$dars ~ dat4$type)
mod5zsum <- summary(mod5z)

mod6z = lm(dat4$teps ~ dat4$type)
mod6zsum <- summary(mod6z)

mod7z = lm(dat4$fc ~ dat4$type)
mod7zsum <- summary(mod7z)

mod8z = lm(dat4$mdeg ~ dat4$type)
mod8zsum <- summary(mod8z)

mod9z = lm(dat4$mod ~ dat4$type)
mod9zsum <- summary(mod9z)

mod10z = lm(dat4$ms ~ dat4$type)
mod10zsum <- summary(mod10z)

mod11z = lm(dat4$madrs ~ dat4$fc + dat4$mdeg + dat4$mod + dat4$ms) #all graph theory measures
mod11zsum <- summary(mod11z)

############ with #855 removed    [I think #855 was an outlier on the madrs plot and Dr. Geier wanted to check if correlation still held with it removed]
dat4ed <- dat4$subj !=  "855" 

    mod11z = lm(dat4$madrs ~ dat4$fc + dat4$mdeg + dat4$mod + dat4$ms) #all graph     theory measures
    mod11zsum <- summary(mod11z)
############

mod12z = lm(dat4$shaps ~ dat4$fc)
mod12zsum <- summary(mod12z)

mod13z = lm(dat4$shaps ~ dat4$fc + dat4$mdeg + dat4$mod + dat4$ms) #all graph theory measures
mod13zsum <- summary(mod13z)
mod13zsum$coefficients[5,3]

#### more models for individual graph metrics predicting 'type' and/or 'shaps' or other anhedonia measures

mod14z = lm(dat4$shaps ~ dat4$mdeg)
mod14zsum <- summary(mod14z)

mod15z = lm(dat4$shaps ~ dat4$mod)
mod15zsum <- summary(mod15z)

mod16z = lm(dat4$shaps ~ dat4$ms)
mod16zsum <- summary(mod16z)

mod17z = lm(dat4$antic ~ dat4$fc + dat4$mdeg + dat4$mod + dat4$ms) #all graph theory measures
mod17zsum <- summary(mod17z)

mod18z = lm(dat4$dars ~ dat4$fc + dat4$mdeg + dat4$mod + dat4$ms) #all graph theory measures
mod18zsum <- summary(mod18z)

mod19z = lm(dat4$teps ~ dat4$fc + dat4$mdeg + dat4$mod + dat4$ms) #all graph theory measures
mod19zsum <- summary(mod19z)

mod20z = lm(dat4$consum ~ dat4$fc + dat4$mdeg + dat4$mod + dat4$ms) #all graph theory measures
mod20zsum <- summary(mod20z)


summary(mod18z)
summary(mod19z)
summary(mod20z)

```



## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
